'use client';
import { Provider } from 'react-redux';
import '../styles/globalstyle.css';
import AuthProvider from './layoutComponents/AuthProvider';
import Navbar from './layoutComponents/Navbar';
import store from '@/store/store';
export const metadata = {
  title: 'Handy Dandy',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="../styles/globalstyle.css" />
      </head>
      <body>
        <Provider store={store}>
          <AuthProvider>
            <header>
              <Navbar />
            </header>
            <div className="container">
              <section>{children}</section>
            </div>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
