import '../styles/globalstyle.css';

export const metadata = {
  title: 'Handy Dandy',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="../styles/globalstyle.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
